
version: '3.9'


volumes:
  IMDB_DATABASE_VOLUME:

services:
  postgre_imdb:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - IMDB_DATABASE_VOLUME:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: mostafa_8888
      POSTGRES_PASSWORD: 12345mostafa12345
      POSTGRES_DB: imdb_database

  redis_broker:
        hostname: imdb_redis_broker
        image: "redis:latest"
        ports: 
            - 6380:6380
            - 6379:6379
