# Generated by Django 4.0.4 on 2022-05-02 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lang', models.CharField(choices=[('German', 'German'), ('English', 'English'), ('Chinese', 'Chinese'), ('Spanish', 'Spanish')], max_length=25)),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('story_line', models.TextField(max_length=500)),
                ('genre', models.CharField(choices=[('Science_Fiction', 'Science_Fiction'), ('Drama', 'Drama'), ('Action', 'Action'), ('Horror', 'Horror')], max_length=25)),
                ('released_date', models.DateField()),
                ('poster', models.ImageField(upload_to='static/movies/%Y/%m/%d/')),
                ('duration_hour', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('duration_min', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('duration_sec', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
            ],
        ),
    ]
