# Generated by Django 4.0.4 on 2022-05-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_post', '0005_person_moviecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('Director', 'Director'), ('Writer', 'Writer'), ('Cinematographer', 'Cinematographer')], max_length=25)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies_post.movie')),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies_post.person')),
            ],
            options={
                'verbose_name_plural': 'MoviesCrew',
            },
        ),
    ]
