# Generated by Django 4.0.4 on 2022-05-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_post', '0007_remove_movie_duration_sec_alter_person_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecast',
            unique_together={('person_name', 'movie', 'character_name')},
        ),
    ]
