# Generated by Django 4.0.4 on 2022-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_post', '0008_alter_moviecast_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecast',
            unique_together={('person_name', 'movie')},
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='character_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
