# Generated by Django 4.0.4 on 2022-05-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_post', '0012_remove_movie_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
